[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/jdcasale/metrics-helper"
authors = ["Josh Casale <joshua.d.casale@gmail.com>"]

[workspace.dependencies]
# Proc-macro dependencies
syn = { version = "2", features = ["full"] }
quote = "1"
proc-macro2 = "1"
darling = "0.20"

# Runtime dependencies
metrics = "0.24"

# Dev dependencies
metrics-util = { version = "0.19", features = ["debugging"] }
tokio = { version = "1", features = ["rt", "macros"] }
